services:
  - type: web
    name: telegram-video-api
    env: python
    region: oregon
    plan: free
    branch: main
    numInstances: 1
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
